runtime: nodejs10
env: standard
instance_class: B1

basic_scaling:
  max_instances: 1
  idle_timeout: 10m

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  DATABASE_URI: mongodb+srv://AzbowDev:4YT02drGnKCgD9Q1@azbowdbs-vj4ck.mongodb.net/LeanSL_dev?retryWrites=true&w=majority
  NODE_ENV: development